# Generated by Django 2.2 on 2019-06-26 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpunchCard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchcard',
            name='desc',
            field=models.CharField(default=1, max_length=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='punchcard',
            name='points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='punchcard',
            name='time_spent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
