# Generated by Django 2.2 on 2019-06-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpunchCard', '0002_auto_20190625_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchcard',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
