# Generated by Django 2.2 on 2019-07-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpunchCard', '0003_auto_20190629_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punchcard',
            name='day',
        ),
        migrations.RemoveField(
            model_name='punchcard',
            name='month',
        ),
        migrations.AddField(
            model_name='punchcard',
            name='date',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
