# Generated by Django 2.2 on 2019-07-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpunchCard', '0004_auto_20190702_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punchcard',
            old_name='time',
            new_name='clockIn',
        ),
        migrations.AddField(
            model_name='punchcard',
            name='clockOut',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
