# Generated by Django 2.2 on 2019-07-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpunchCard', '0005_auto_20190702_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punchcard',
            name='clockIn',
        ),
        migrations.RemoveField(
            model_name='punchcard',
            name='clockOut',
        ),
        migrations.RemoveField(
            model_name='punchcard',
            name='date',
        ),
        migrations.AddField(
            model_name='punchcard',
            name='clock',
            field=models.CharField(default=1, max_length=9999),
            preserve_default=False,
        ),
    ]
