# Generated by Django 2.2 on 2019-07-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EpunchCard', '0006_auto_20190708_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punchcard',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='punchcard',
            name='points',
        ),
        migrations.RemoveField(
            model_name='punchcard',
            name='time_spent',
        ),
    ]
