# Generated by Django 2.2 on 2019-07-14 21:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('EpunchCard', '0007_auto_20190712_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchcard',
            name='clock',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
