# Generated by Django 2.2 on 2019-12-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpunchCard', '0008_auto_20190714_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchcard',
            name='total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4000),
        ),
    ]
