# Generated by Django 2.2 on 2019-12-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpunchCard', '0009_punchcard_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punchcard',
            name='total',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4000),
        ),
    ]
