# Generated by Django 2.2 on 2019-12-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EpunchCard', '0010_auto_20191205_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='admin_id',
            field=models.CharField(default=0, max_length=2000),
        ),
    ]
